<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>PinguApps.Aspire.Hosting.Dashboard.Railway</PackageId>
    <PackageIcon>icon.png</PackageIcon>
    <AssemblyName>PinguApps.Aspire.Hosting.Dashboard.Railway</AssemblyName>
    <Description>Authenticated standalone Aspire dashboard publishing for Railway.</Description>
    <EnableAspireIntegrationAnalyzers>true</EnableAspireIntegrationAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" />
    <PackageReference Include="PinguApps.Aspire.Hosting.Railway" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="icon.png" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
